global:
  scrape_interval: 15s  # Scraping every 15 seconds

scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8081']  # Use 'host.docker.internal' for Docker to access localhost